### ISSUE TITLE
Finish Views for UI

### ISSUE THREAD

**Issue by jchionak** [Group-143-The-Dream-Team-CSC207H1-UofT/podcast-app#24]
Views that need to be finished:

- [x] Podcasts View (displays all the uploaded podcasts, contains a search button that brings user to the search view)
- [x] Podcast View (displays information of specific podcast as well as a list of episodes of that podcast)
- [x] Episode View (displays episode information, play button, transcript, and summary button to generate a summary of the podcast)

**Comment by DrDabbidy** [comment]
These were all completed today and yesterday.
